[tool.poetry]
name = "workflow-dispatcher"
version = "0.1.0"
description = ""
authors = ["Tomohiko Ozawa <kota65535@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.11"
requests = "2.31.0"
jinja2 = "3.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
